updated ec2-metadata script to 0.1.1

diff --git a/files/default/ec2-metadata b/files/default/ec2-metadata
--- a/files/default/ec2-metadata
+++ b/files/default/ec2-metadata
@@ -13,11 +13,11 @@
 
 function print_help()
 {
-echo "ec2-metadata v0.1
+echo "ec2-metadata v0.1.1
 Use to retrieve EC2 instance metadata from within a running EC2 instance. 
 e.g. to retrieve instance id: ec2-metadata -i
-     to retrieve ami id: ec2-metadata -a
-     to get help: ec2-metadata --help
+		 to retrieve ami id: ec2-metadata -a
+		 to get help: ec2-metadata --help
 For more information on Amazon EC2 instance meta-data, refer to the documentation at
 http://docs.amazonwebservices.com/AWSEC2/2008-05-05/DeveloperGuide/AESDG-chapter-instancedata.html
 
@@ -48,274 +48,83 @@ Options:
 #check some basic configurations before running the code
 function chk_config()
 {
- #check if run inside an ec2-instance
- x=$(curl -s http://169.254.169.254/)
- if [ $? -gt 0 ]; then
-    echo '[ERROR] Command not valid outside EC2 instance. Please run this command within a running EC2 instance.'
-    exit 1
- fi
+	#check if run inside an ec2-instance
+	x=$(curl -s http://169.254.169.254/)
+	if [ $? -gt 0 ]; then
+		echo '[ERROR] Command not valid outside EC2 instance. Please run this command within a running EC2 instance.'
+		exit 1
+	fi
 }
 
-#print ami-id
-function print_ami-id()
-{
-echo -n 'ami-id: '
-x=$(curl -s http://169.254.169.254/latest/meta-data/ami-id)
-if [ $(echo $x|grep 404|wc -l) -eq 0 ]; then
-   echo $x
-   else
-   echo not available
-fi
-}
-
-#print ami-launch-index
-function print_ami-launch-index()
-{
-echo -n 'ami-launch-index: '
-x=$(curl -s http://169.254.169.254/latest/meta-data/ami-launch-index)
-if [ $(echo $x|grep 404|wc -l) -eq 0 ]; then
-   echo $x
-   else
-   echo not available
-fi
-}
-
-#print ami-manifest-path
-function print_ami-manifest-path()
-{
-echo -n 'ami-manifest-path: '
-x=$(curl -s http://169.254.169.254/latest/meta-data/ami-manifest-path)
-if [ $(echo $x|grep 404|wc -l) -eq 0 ]; then
-   echo $x
-   else
-   echo not available
-fi
-}
-
-#print ancestor-amis
-function print_ancestor-ami-ids()
-{
-echo -n 'ancestor-ami-ids: '
-x=$(curl -s http://169.254.169.254/latest/meta-data/ancestor-ami-ids)
-if [ $(echo $x|grep 404|wc -l) -eq 0 ]; then
-   echo $x
-   else
-   echo not available
-fi
+#print standard metric
+function print_normal_metric() {
+	metric_path=$2
+	echo -n $1": "
+	RESPONSE=$(curl -fs http://169.254.169.254/latest/${metric_path}/)
+	if [ $? == 0 ]; then
+		echo $RESPONSE
+	else
+		echo not available
+	fi
 }
 
 #print block-device-mapping
 function print_block-device-mapping()
 {
 echo 'block-device-mapping: '
-x=$(curl -s http://169.254.169.254/latest/meta-data/block-device-mapping/)
-if [ $(echo $x|grep 404|wc -l) -eq 0 ]; then
-   for i in $x; do
-       echo -e '\t' $i: $(curl -s http://169.254.169.254/latest/meta-data/block-device-mapping/$i)
-   done
-   else
-   echo not available
-fi
-}
-
-#print instance-id
-function print_instance-id()
-{
-echo -n 'instance-id: '
-x=$(curl -s http://169.254.169.254/latest/meta-data/instance-id)
-if [ $(echo $x|grep 404|wc -l) -eq 0 ]; then
-   echo $x
-   else
-   echo not available
-fi
-}
-
-#print instance-type
-function print_instance-type()
-{
-echo -n 'instance-type: '
-x=$(curl -s http://169.254.169.254/latest/meta-data/instance-type)
-if [ $(echo $x|grep 404|wc -l) -eq 0 ]; then 
-   echo $x
-   else
-   echo not available
-fi
-}
-
-#print local-hostname
-function print_local-hostname()
-{
-echo -n 'local-hostname: '
-x=$(curl -s http://169.254.169.254/latest/meta-data/local-hostname)
-if [ $(echo $x|grep 404|wc -l) -eq 0 ]; then
-   echo $x
-   else
-   echo not available
-fi
-}
-
-#print local-ipv4
-function print_local-ipv4()
-{
-echo -n 'local-ipv4: '
-x=$(curl -s http://169.254.169.254/latest/meta-data/local-ipv4)
-if [ $(echo $x|grep 404|wc -l) -eq 0 ]; then
-   echo $x
-   else
-   echo not available
-fi
-}
-
-#print kernel-id
-function print_kernel-id()
-{
-echo -n 'kernel-id: '
-x=$(curl -s http://169.254.169.254/latest/meta-data/kernel-id)
-if [ $(echo $x|grep 404|wc -l) -eq 0 ]; then
-   echo $x
-   else
-   echo not available
-fi
-}
-
-#print placement
-function print_placement()
-{
-echo -n 'placement: '
-x=$(curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone)
-if [ $(echo $x|grep 404|wc -l) -eq 0 ]; then
-   echo $x
-   else
-   echo not available
-fi
-}
-
-#print product-codes
-function print_product-codes()
-{
-echo -n 'product-codes: '
-x=$(curl -s http://169.254.169.254/latest/meta-data/product-codes)
-if [ $(echo $x|grep 404|wc -l) -eq 0 ]; then
-   echo $x
-   else
-   echo not available
-fi
-}
-
-#print public-hostname
-function print_public-hostname()
-{
-echo -n 'public-hostname: '
-x=$(curl -s http://169.254.169.254/latest/meta-data/public-hostname)
-if [ $(echo $x|grep 404|wc -l) -eq 0 ]; then
-   echo $x
-   else
-   echo not available
-fi
-}
-
-#print public-ipv4
-function print_public-ipv4()
-{
-echo -n 'public-ipv4: '
-x=$(curl -s http://169.254.169.254/latest/meta-data/public-ipv4)
-if [ $(echo $x|grep 404|wc -l) -eq 0 ]; then
-   echo $x
-   else
-   echo not available
+x=$(curl -fs http://169.254.169.254/latest/meta-data/block-device-mapping/)
+if [ $? -eq 0 ]; then
+	for i in $x; do
+		echo -e '\t' $i: $(curl -s http://169.254.169.254/latest/meta-data/block-device-mapping/$i)
+	done
+else
+	echo not available
 fi
 }
 
 #print public-keys
 function print_public-keys()
 {
-echo 'public-keys: '
-x=$(curl -s http://169.254.169.254/latest/meta-data/public-keys/)
-if [ $(echo $x|grep 404|wc -l) -eq 0 ]; then
-   for i in $x; do
-   index=$(echo $i|cut -d = -f 1)
-   keyname=$(echo $i|cut -d = -f 2)
-   echo keyname:$keyname
-   echo index:$index
-   format=$(curl -s http://169.254.169.254/latest/meta-data/public-keys/$index/)
-   echo format:$format
-   echo 'key:(begins from next line)'
-   echo $(curl -s http://169.254.169.254/latest/meta-data/public-keys/$index/$format)
-   done
-   else
-   echo not available
-fi
+	echo 'public-keys: '
+	x=$(curl -fs http://169.254.169.254/latest/meta-data/public-keys/)
+	if [ $? -eq 0 ]; then
+		for i in $x; do
+			index=$(echo $i|cut -d = -f 1)
+			keyname=$(echo $i|cut -d = -f 2)
+			echo keyname:$keyname
+			echo index:$index
+			format=$(curl -s http://169.254.169.254/latest/meta-data/public-keys/$index/)
+			echo format:$format
+			echo 'key:(begins from next line)'
+			echo $(curl -s http://169.254.169.254/latest/meta-data/public-keys/$index/$format)
+		done
+	else
+		echo not available
+	fi
 }
 
-#print ramdisk-id
-function print_ramdisk-id()
-{
-echo -n 'ramdisk-id: '
-x=$(curl -s http://169.254.169.254/latest/meta-data/ramdisk-id)
-if [ $(echo $x|grep 404|wc -l) -eq 0 ]; then
-   echo $x
-   else
-   echo not available
-fi
-}
-
-#print reservation-id
-function print_reservation-id()
-{
-echo -n 'reservation-id: '
-x=$(curl -s http://169.254.169.254/latest/meta-data/reservation-id)
-if [ $(echo $x|grep 404|wc -l) -eq 0 ]; then
-   echo $x
-   else
-   echo not available
-fi
-}
-
-#print security-groups
-function print_security-groups()
-{
-echo -n 'security-groups: '
-x=$(curl -s http://169.254.169.254/latest/meta-data/security-groups)
-if [ $(echo $x|grep 404|wc -l) -eq 0 ]; then
-   echo $x
-   else
-   echo not available
-fi
-}
-
-#print user data
-function print_user_data()
-{
-echo -n 'user-data: '
-x=$(curl -s http://169.254.169.254/latest/user-data)
-if [ $(echo $x|grep 404|wc -l) -eq 0 ]; then
-   echo $x
-   else
-   echo not available
-fi
-}
 
 function print_all()
 {
-print_ami-id
-print_ami-launch-index
-print_ami-manifest-path
-print_ancestor-ami-ids
-print_block-device-mapping
-print_instance-id
-print_instance-type
-print_local-hostname
-print_local-ipv4
-print_kernel-id
-print_placement
-print_product-codes
-print_public-hostname
-print_public-ipv4
-print_public-keys
-print_ramdisk-id
-print_reservation-id
-print_security-groups
-print_user_data
+	print_normal_metric ami-id meta-data/ami-id
+	print_normal_metric ami-launch-index meta-data/ami-launch-index
+	print_normal_metric ami-manifest-path meta-data/ami-manifest-path
+	print_normal_metric ancestor-ami-ids meta-data/ancestor-ami-ids
+	print_block-device-mapping
+	print_normal_metric instance-id meta-data/instance-id
+	print_normal_metric instance-type meta-data/instance-type
+	print_normal_metric local-hostname meta-data/local-hostname
+	print_normal_metric local-ipv4 meta-data/local-ipv4
+	print_normal_metric kernel-id meta-data/kernel-id
+	print_normal_metric placement meta-data/placement/availability-zone
+	print_normal_metric product-codes meta-data/product-codes
+	print_normal_metric public-hostname meta-data/public-hostname
+	print_normal_metric public-ipv4 meta-data/public-ipv4
+	print_public-keys
+	print_normal_metric ramdisk-id /meta-data/ramdisk-id
+	print_normal_metric reservation-id /meta-data/reservation-id
+	print_normal_metric security-groups meta-data/security-groups
+	print_normal_metric user-data user-data
 }
 
 #check if run inside an EC2 instance
@@ -323,58 +132,58 @@ chk_config
 
 #command called in default mode
 if [ "$#" -eq 0 ]; then
-print_all
+	print_all
 fi
 
 #start processing command line arguments
 while [ "$1" != "" ]; do
-    case $1 in
-        -a | --ami-id )                print_ami-id
-                                       ;;
-        -l | --ami-launch-index )      print_ami-launch-index
-                                       ;;
-	-m | --ami-manifest-path )     print_ami-manifest-path
-	                               ;;
-	-n | --ancestor-ami-ids )      print_ancestor-ami-ids
-	                               ;;
-        -b | --block-device-mapping )  print_block-device-mapping
-                                       ;;
-	-i | --instance-id )           print_instance-id
-	                               ;;
-        -t | --instance-type )         print_instance-type
-                                       ;;
-	-h | --local-hostname )        print_local-hostname
-	                               ;;
-	-o | --local-ipv4 )            print_local-ipv4
-	                               ;;
-	-k | --kernel-id )             print_kernel-id
-	                               ;;
-	-z | --availability-zone )     print_placement
-	                               ;;
-	-c | --product-codes )         print_product-codes
-	                               ;;
-	-p | --public-hostname )       print_public-hostname
-	                               ;;
-	-v | --public-ipv4 )           print_public-ipv4
-	                               ;;
+	case $1 in
+	-a | --ami-id )                print_normal_metric ami-id meta-data/ami-id
+																 ;;
+	-l | --ami-launch-index )      print_normal_metric ami-launch-index meta-data/ami-launch-index
+																 ;;
+	-m | --ami-manifest-path )     print_normal_metric ami-manifest-path meta-data/ami-manifest-path
+																 ;;
+	-n | --ancestor-ami-ids )      print_normal_metric ancestor-ami-ids meta-data/ancestor-ami-ids
+																 ;;
+	-b | --block-device-mapping )  print_block-device-mapping
+																 ;;
+	-i | --instance-id )           print_normal_metric instance-id meta-data/instance-id
+																 ;;
+	-t | --instance-type )         print_normal_metric instance-type meta-data/instance-type
+																 ;;
+	-h | --local-hostname )        print_normal_metric local-hostname meta-data/local-hostname
+																 ;;
+	-o | --local-ipv4 )            print_normal_metric local-ipv4 meta-data/local-ipv4
+																 ;;
+	-k | --kernel-id )             print_normal_metric kernel-id meta-data/kernel-id
+																 ;;
+	-z | --availability-zone )     print_normal_metric placement meta-data/placement/availability-zone
+																 ;;
+	-c | --product-codes )         print_normal_metric product-codes meta-data/product-codes
+																 ;;
+	-p | --public-hostname )       print_normal_metric public-hostname meta-data/public-hostname
+																 ;;
+	-v | --public-ipv4 )           print_normal_metric public-ipv4 meta-data/public-ipv4
+																 ;;
 	-u | --public-keys )           print_public-keys
-	                               ;;
-	-r | --ramdisk-id )            print_ramdisk-id
-	                               ;;
-	-e | --reservation-id )        print_reservation-id
-	                               ;;
-	-s | --security-groups )       print_security-groups
-	                               ;;
-	-d | --user-data )             print_user_data
-                                       ;;
-        -h | --help )                  print_help
-                                       exit
-                                       ;;
-        --all )                        print_all
-	                               exit 
-	                               ;;
-        * )                            print_help
-                                       exit 1
-    esac
-    shift
+																 ;;
+	-r | --ramdisk-id )            print_normal_metric ramdisk-id /meta-data/ramdisk-id
+																 ;;
+	-e | --reservation-id )        print_normal_metric reservation-id /meta-data/reservation-id
+																 ;;
+	-s | --security-groups )       print_normal_metric security-groups meta-data/security-groups
+																 ;;
+	-d | --user-data )             print_normal_metric user-data user-data
+																 ;;
+	-h | --help )                  print_help
+								 exit
+																 ;;
+	--all )                        print_all
+								 exit 
+																 ;;
+	* )                            print_help
+								 exit 1
+	esac
+	shift
 done
